apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dad-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.directaerialdelivery.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dad-backend-service
            port:
              number: 80
